### ISSUE TITLE
Certains énoncés absents des corrigés

### ISSUE THREAD

**Issue by ghost** [jbreizh/actimaths#2]
Bonjour,

Je signale cette incohérence, que je vais essayer de corriger dans le code : certains corrigés sont affichés sans l'énoncé. C'est le cas des séries : "Ecrire en chiffres" et "Ecrire en lettres".

Amicalement,
Kellogs

**Comment by jbreizh** [comment]
Corrigé pour les exercices cités. J'ai essayé de faire au mieux pour l'encadrement de la solution.
