### ISSUE TITLE
Afficher titre, établissement, auteur et date dans la version papier

### ISSUE THREAD

**Issue by ghost** [jbreizh/actimaths#3]
A la différence de la version Beamer, la version papier n'affiche pas : le titre, l'établissement, l'auteur, la date. Je vais essayer de corriger dans le code. C'est important, car le lundi matin, quand on se retrouve face à la photocopieuse avec plusieurs tas à photocopier, mieux vaut que ces informations soient affichées.

On peut facilement modifier le template à la main.

Je regarderai cela dans les prochaines semaines.

**Comment by jbreizh** [comment]
Bon j'ai corrigé ça dans la version develop (un peu d'organisation ne fait pas de mal)
a+
